import os

# -------- BOT CONFIG --------
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN")
LLM_API_KEY = os.environ.get("LLM_API_KEY")

# -------- USER IDS --------
BAGGINS_ID = "USER_ID_PLACEHOLDER"
SNAZZYDADDY_ID = "USER_ID_PLACEHOLDER"
PHROGSLEG_ID = "1072729769428398080"  # From the DM file name
CORN_ID = "USER_ID_PLACEHOLDER"
PUGMONKEY_ID = "USER_ID_PLACEHOLDER"
MEATBRO_ID = "USER_ID_PLACEHOLDER"
RESTORT_ID = "USER_ID_PLACEHOLDER"
TBL_ID = "USER_ID_PLACEHOLDER"
EVAN_ID = "USER_ID_PLACEHOLDER"
DROID_ID = "USER_ID_PLACEHOLDER"
